#
# Sample pipelinerun for deploying an App Connect Enterprise integration server
#
# You need to modify this with details of your own App Connect application.
#
# This sample shows how to deploy a simple stand-alone App Connect application

apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: ace-deploy-
spec:
  serviceAccountName: pipeline-deployer-serviceaccount
  params:
    # ########################################################
    # where to run the App Connect application
    # ########################################################
    # what to call the IntegrationServer that runs your application
    - name: integration-server-name
      value: "hello-world"
    # where to run your application
    - name: ace-namespace
      value: "ace-demo"

    # ########################################################
    # where to find the projects to create
    # ########################################################
    # location of the git repository with your application
    - name: git-repository
      value: "https://github.com/khongks/app-connect-tekton-pipeline"

    # name of the App Connect project to deploy
    #  This should be the name of a folder in ace-projects
    - name: ace-project-name
      value: "simple-demo"

    # name of an App Connect test project
    #  This is used to verify the bar before the new
    #  Integration Server is deployed
    #  This should be the name of a folder in ace-projects
    - name: test-project-name
      value: "simple-demo_Test"

    - name: app-connect-enterprise-version
      value: "12.0.9.0-r1"
    
    - name: app-connect-enterprise-license
      value: "L-LFMR-BTD75V"

    - name: app-connect-enterprise-base-image
      value: cp.icr.io/cp/appc/ace-server-prod@sha256:246828d9f89c4ed3a6719cd3e4b71b1dec382f848c9bf9c28156f78fa05bc4e7

  pipelineRef:
    name: pipeline-ace-integration-server

  workspaces:
    - name: pipeline-shared-workspace
      volumeClaimTemplate:
        spec:
          storageClassName: ocs-storagecluster-cephfs
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 100Mi

