apiVersion: integration.ibm.com/v1beta1
kind: PlatformNavigator
metadata:
  name: navigator
  namespace: integration
spec:
  license:
    accept: true
    license: L-YBXJ-ADJNSM
  mqDashboard: true
  replicas: 1
  storage:
    class: managed-nfs-storage
  version: 2023.2.1
